# Generated by Django 2.2 on 2019-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190504_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nepersnt',
            field=models.CharField(default='compny', max_length=50, verbose_name='Person Name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='nopersnt',
            field=models.CharField(default='number', max_length=10, verbose_name='Person Number'),
        ),
    ]
