# Generated by Django 2.2 on 2019-05-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190509_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nepersnt',
            field=models.CharField(default=None, max_length=50, verbose_name='Person Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nopersnt',
            field=models.CharField(default=None, max_length=10, verbose_name='Person Number'),
        ),
    ]
