# Generated by Django 2.2 on 2019-06-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190605_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_logo',
            field=models.ImageField(default='default.jpg', upload_to='logo_co'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(default='default.jpg', upload_to='post_co'),
        ),
    ]
