# Generated by Django 2.2 on 2019-09-16 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20190605_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=100)),
                ('name_job', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-post_date',),
            },
        ),
    ]
