# Generated by Django 2.2 on 2019-09-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_jobnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnew',
            name='certificate',
            field=models.CharField(max_length=100, verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='jobnew',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobnew',
            name='mobile_number',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='jobnew',
            name='name_employee',
            field=models.CharField(max_length=100, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='jobnew',
            name='name_job',
            field=models.CharField(max_length=100, verbose_name='Job Name'),
        ),
    ]
