# Generated by Django 2.2 on 2019-09-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190917_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobnew',
            name='author',
        ),
    ]
