# Generated by Django 2.2 on 2019-09-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_jobnew_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobnew',
            new_name='Jobrequest',
        ),
    ]
