# Generated by Django 2.2 on 2019-09-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_jobnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='cv',
            field=models.FileField(default=None, upload_to='', verbose_name='Uploads CV'),
        ),
    ]
