# Generated by Django 2.2 on 2019-09-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_jobrequest_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='cv',
            field=models.FileField(default='default.jpg', upload_to='Upload_CV', verbose_name='Uploads CV'),
        ),
    ]
