# Generated by Django 2.2 on 2019-09-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190930_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='cv',
            field=models.FileField(default=0, upload_to='Upload_CV', verbose_name='Uploads CV'),
        ),
    ]
