# Generated by Django 2.2 on 2019-09-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190930_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='cv',
            field=models.FileField(default=1, upload_to='Upload_CV', verbose_name='Uploads CV'),
        ),
    ]
