# Generated by Django 2.2 on 2019-09-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190930_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='cv',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='uploads_cv',
            field=models.FileField(default=1, upload_to='upload_cv', verbose_name='Uploads CV'),
        ),
    ]
