# Generated by Django 2.2 on 2019-09-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190930_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='uploads_cv',
        ),
    ]
