# Generated by Django 2.2 on 2019-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_jobrequest_uploads_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='uploaad_cv',
            field=models.FileField(blank=True, null=True, upload_to='logo_co/'),
        ),
    ]
