# Generated by Django 2.2 on 2019-10-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_jobrequest_uploaad_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='uploaad_cv',
            field=models.FileField(blank=True, null=True, upload_to='upload_cv'),
        ),
    ]
