# Generated by Django 2.2 on 2019-10-02 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20191002_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'ordering': ('-post_date',)},
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='certificate',
            field=models.CharField(default=None, max_length=100, verbose_name='Certificate'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='description',
            field=models.TextField(default=None, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.CharField(default=None, max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='name_employee',
            field=models.CharField(default=None, max_length=100, verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='name_job',
            field=models.CharField(default=None, max_length=100, verbose_name='Job Name'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='uploaad_cv',
            field=models.FileField(blank=True, null=True, upload_to='upload_cv'),
        ),
    ]
