# Generated by Django 2.2 on 2019-10-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20191002_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Order Details'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.IntegerField(default=None, max_length=10, verbose_name='Mobile Number'),
        ),
    ]
