# Generated by Django 2.2 on 2019-10-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20191013_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Mobile Number'),
        ),
    ]
