# Generated by Django 2.2 on 2019-10-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20191016_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
