# Generated by Django 2.2 on 2019-10-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20191017_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
