# Generated by Django 2.2 on 2019-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20191017_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
