# Generated by Django 2.2 on 2019-10-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20191020_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='mobile_number'),
        ),
    ]
