# Generated by Django 2.2 on 2019-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20191020_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.IntegerField(default=None, verbose_name='Mobile_number'),
        ),
    ]
