# Generated by Django 2.2 on 2019-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20191020_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=None, verbose_name='Mobile_number'),
        ),
    ]
