# Generated by Django 2.2 on 2019-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20191021_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='email_employe',
            field=models.EmailField(default=None, max_length=100, verbose_name='Email'),
        ),
    ]
