# Generated by Django 2.2 on 2019-10-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_jobrequest_email_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=None, verbose_name='Mobile_number'),
        ),
    ]
