# Generated by Django 2.2 on 2019-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20191024_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Mobile_number'),
        ),
    ]
